# Upload Group Data to the Data Management System {#DMGroupData}


* Server: (http://wbgmsrech001/povcalnet/DB_Management.aspx)

* Given that anyone may have access to the Data Base Management Syste, the username and password are not provided in this document. 

## Preparing the data

Once the Group Data is received from the regional focal point of the Poverty GP, It has to be copied and pasted into a text file. Two columns of data must be pasted into the text file; one for weight and one for welfare, which may come in three different varieties and are clearly explain the [Povcalnet Website](http://iresearch.worldbank.org/PovcalNet/povcalculator.aspx). For the case of China 2016, which is the database used as example in this text, data comes in type 5 format,[^1] which means that the weight variable is the share of the population in a given quantile and the welfare variable is the mean of welfare therein.  If the data comes broken down by urban and rural population, it is necessary to create one text file for each distribution. 

### Naming convention

Text files must be saved with the following naming convention, 

> `ccccgXX.T0F`, where the only literal piece of the naming convention is `T0`. All the other are as follows, 

* `cccc` refers to the name of the country
* `g` refers to the geographic area: `r` for rural, `u` for urban, and `n` for national 
* `XX` stands for the last two digits of the corresponding year of the survey. For example, if the year is 2016, then `XX` would be 16. 
* `F` refers to the type formatting of the data. In the case of China 2016 it would be 5. 



[^1]: Even though there are only three types of grouped data, they are labeled type 1, type 2, and type5
