# Introduction {#intro}

PovcalNet is an interactive computational tool that allows you to replicate the calculations made by the World Bank's researchers in estimating the extent of absolute poverty in the world. PovcalNet also allows you to calculate the poverty measures under different assumptions and to assemble the estimates using alternative economy groupings or for any set of individual economies of the user’s choosing. PovcalNet is self-contained; it has reliable built-in software that quickly does the relevant calculations for you from the built-in database.  

In March 2019, the World Bank released revised estimates of global poverty from 1981 to 2015 based on 2011 PPPs. The new poverty estimates combine Purchasing Power Parity (PPP) exchange rates for household consumption from the 2011 International Comparison Program with data from more than one thousand five hundred household surveys across 164 economies in the world, including 26 high income economies not included in PovcalNet’s geographic regions. Over two million randomly sampled households were interviewed for the 2015 estimate, representing 65 percent of the population of the whole world.

PovcalNet is the source of, and allows users to replicate, the Bank's official global, regional and internationally comparable economy level poverty estimates published in the [World Development Indicators](http://datatopics.worldbank.org/world-development-indicators/) and the [Poverty and Shared Prosperity report](https://openknowledge.worldbank.org/bitstream/handle/10986/25078/9781464809583.pdf). It also provides crucial inputs to the [Poverty and Equity Data Portal](http://povertydata.worldbank.org/poverty/home/). If you would like to duplicate the World Bank's regional poverty estimates please click the first button; or go to the second button to form your own group of economies. PovcalNet uses unit-record data whenever possible. For other cases, grouped distributions are used. New survey data become available to us on a continuous basis and these will be added to PovcalNet in regular updates.

*PovcalNet was developed for the sole purpose of public replication of the World Bank’s poverty measures for its widely used international poverty lines, including $1.90 a day and $3.20 a day in 2011 PPP. The methods built into PovcalNet are considered reliable for that purpose. However, we cannot be confident that the methods work well for other purposes, including tracing out the entire distribution of income. We would especially warn that estimates of the densities near the bottom and top tails of the distribution could be quite unreliable, and no attempt has been made by the Bank’s staff to validate the tool for such purposes.*
