# LIS Data {#lis-data}

Some of the countries that are not available in DataLibWeb (or additional years for countries that are included in DLW) can be found in the
repository of the [LIS Cross-National Data
Center](https://www.lisdatacenter.org/) (hereafter, LIS). LIS provides a
remote-execution system,
[LISSY,](http://www.lisdatacenter.org/data-access/lissy/) that allows us
interact with their micrdata without having access to the individual records. We
have developed a set of Stata do-files to interact with the LIS system and
aggregate the welfare distribution of countries of interest to 400 bins. Then,
these data is organized locally and shared with the Poverty GP to be included in
DataLibWeb as a collection independent from GPWG.

## The LIS\_data repository

In order to work with the LIS data you need to clone the repository
[PovcalNet-Team/LIS/\_data.](https://github.com/PovcalNet-Team/LIS_data) You
will find in there three folders, *00.LIS\_output*, *01.programs*, and
*02.data*.

## Interacting with LISSY

::: {.bg-light-green}
::: {.tl}
**Marthis:**
:::

::: {.dark-blue}
-   How to open an account in LISSY
-   How to log in and work inside LISSY
:::
:::

## Getting the 400 bins from LISSY

::: {.bg-light-green}
::: {.tl}
**Marthis:**
:::

::: {.dark-blue}
-   What parts of the do-file we should modify
-   How and where to save the results (Exaplain the naming so it could be used
    in the `02.LIS_organize_output.do` file)
:::
:::

## From Text file to datalibweb structure

We now need to convert the text files generated by the LISSY system to
data files suitable for datalibweb. This structure is suggested by the
[International Household Survey Network](https://ihsn.org/) (IHSN). Once the
data is saved in folder `00.LIS_output` you need to execute the file
**`02.LIS_organize_output.do`**. This file is designed to be executed in just one
go. However, it can be run in sections taking advantage of the different
[frames](https://www.stata.com/new-in-stata/multiple-datasets-in-memory/) along
the code.

Before you execute this code, you need to ensure a few things,

### 1. Get `rcall` working in your computer

The text files are no longer processed in Stata but in R. To avoid
changing systems, we need to execute R code directly from Stata. In order to do
this, you need to install R in your computer and also the
Stata command `rcall`. The do-file `02.LIS_organize_output.do` will check if you
have it installed and will install it for you in case it is not. However, you
can run the lines below to make sure everything is working fine. Also, you can
take a look at the help file of `rcall` to get familiar with it.

```{stata, eval = FALSE}
cap which rcall
if (_rc) {
	cap which github
	if (_rc) {
		net install github, from("https://haghish.github.io/github/")
	}
	github install haghish/rcall, stable
}
```

### 2. Personal Drive {.unnumbered}

Make sure to add your UPI to the appropriate sections by typing
`` disp lower("`c(username)'") `` , following the example below,

```{stata, eval = FALSE}
if (lower("`c(username)'") == "wbxxxxx") {
	local dir "c:/Users/wbxxxxx/OneDrive - WBG/WorldBank/DECDG/PovcalNet Team/LIS_data"
}
```

### 3. Directives of the code {.unnumbered}

This do-file works like an ado-file in the sense that the output depends on the
value of some local macros,

```{stata, eval = FALSE}
global update_surveynames = 1 // 1 to update survey names.
global replace            = 0 // 1 to replace data in memory even if it has not changed
global p_drive_output_dir = 0 // 1 to use default Vintage_control folder
```

If local `update_surveynames` is set to 1, the code will load the sheet
`LIS_survname` from the file `02.data/_aux/LIS datasets.xlsx` and updated
the file `02.data/_aux/LIS_survname.dta`. If `replace` is set to 1, the code
will replace any output with the same name. Otherwise, it will create a new
vintage version *if the two files are different*. If they are not different, the
code will do nothing. local `p_drive_output_dir` is deprecated, so you must
leave it as **0**.

### 4. Pattern of the text files {.unnumbered}

When the text files with the information from LIS are stored in `00.LIS_output`,
they should be stored in a systematic way so that they could be loaded and
processed at the same time. This can be done by specifying in a matching regular
expression in local `pattern`. For instance, all the files downloaded in
December, 2020 could by loaded and processed using the directive,
`local pattern = "LISSY_Dec2020.*txt"`.

### 5. Output {.unnumbered}

When the do-file is concluded, it saves the file `02.data/create_dta_status.dta`
with the status of all the surveys processed.

## Compare new LIS data to Datalibweb inventory

To identify what data is new and what data has changed with respect to the one
available in datalibweb, you need to execute do-file `03.LIS_compare_dlw.do`.
Again, this do-file is intended to be executed in one run, but you can do it in
parts taking advantage of the different frames. At the end of the execution, the
file `02.data/comparison_results.dta` is created. This file contains three
important variables `wf`, `wt`, and `gn`, which correspond to the ratio of
welfare means, weight means, and Gini coefficient between the data in datalibweb
and the data in the folder, `p:/01.PovcalNet/03.QA/06.LIS/03.Vintage_control`.

You should only send to the Poverty GP those surveys for which at least one of
these three variables is different from 1.

## The Excel file `LIS datasets.xlsx`

::: {.bg-light-green}
::: {.dark-red}
Marthis:
:::

Explanation of the Excel file with the name of the surveys.
:::

## Prepare data for the Poverty GP

Finally, do-file `04.Append_new_LIS_bases.do` prepares the data to be shared
with the Poverty GP.

[Marthis:Could please explain the whole process? Do we have additional do-files
for this part? If we do, we need to add them to the repository.]{.bg-light-green
.dark-red}

