# Update the Master file {#master-file}

In the previous chapters we have seen how to update different sheets of the
master file. In this chapter we basically summarize and reference to the
specific location in which we explain how to update each spreadsheet.

-   ***Population**.* Section \@ref(population).

-   ***RegionLookup**.* Updated manually

-   ***CountryList**.* Updated manually. Right now, it is the source of the
    country_list auxiliary file in PIP. [Is there a way to update this
    automatically? Is this information somewhere else?]{.red}

-   ***CountyLooskUp**.* Updated manually.

-   ***CurrencyConversion**.* Updated Manually. The reason for this is that in
    the *Surveymean* sheet there is an additional columns for taking currency
    conversion into *account.* This double-source availability of currency
    conversion is avoided in PIP, where the information is automatically updated
    from the information available in DLW.

-   ***CPI***. Section \@ref(cpi-and-ppp).

-   ***PPP**.* Section \@ref(cpi-and-ppp).

-   ***GDP**.* Section \@ref(gdp-and-consumption-pce).

-   ***PCE**.* Section \@ref(gdp-and-consumption-pce).

-   ***SurveyInfo**.* @ref(SurveyInfo-master-file).

-   ***SurveyMean**.* Section \@ref(master-objectives).

Just make sure you have updated the master file following the instructions in
each of the sections above.
